# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

workflows:
  sample:
    jobs:
      build:
        - environment:
          IMAGE_NAME: gaspardc/test-cicd
        docker:
          - image: circleci/buildpack-deps:stretch
        steps:
          - checkout
          - setup_remote_docker
          - run:
            name: Build Docker image
            command: docker build -t $IMAGE_NAME:latest .